--- # Lenguaje de programacion utilizado
language: node_js

after_success:
  - bash <(curl -s https://codecov.io/bash) -t 9b641e22-b814-4b3b-b256-41995102d520

env:
  - CODECOV_TOKEN="9b641e22-b814-4b3b-b256-41995102d520"


script:
  - npm test