--- # Lenguaje de programacion utilizado
language: node_js

after_success:
  - bash <(curl -s https://codecov.io/bash)

env:
  - CODECOV_TOKEN="75a3c18b-fec3-4c97-8090-34931a4d00a5"

script:
  - npm test